# Generated by Django 2.2.dev20180801155202 on 2018-08-02 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20180802_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficlight',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='trafficlight',
            old_name='logitude',
            new_name='lng',
        ),
    ]
